### ISSUE TITLE
Verbose SQL logging

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/horta-hell#242]
Currently horta logs every SQL statement. It should not.

**Comment by Newlifer** [comment]
Should be

**Comment by ForNeVeR** [comment]
@Newlifer, state your purpose. Are you mixer?

**Comment by Newlifer** [comment]
@ForNeVeR, nope, I am a blender.

**Comment by ForNeVeR** [comment]
`Error 0x667: subject is not a mixer.` Termination request pending.
