### ISSUE TITLE
Pet::processTick sucks

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/horta-hell#278]
This method is such improperly written so I cannot even find the proper words to express it.

**Comment by rexim** [comment]
Most of the changes in this method was made by some strange user with yellow avatar: https://github.com/codingteam/horta-hell/blame/97946d8f8214425ce7a021899fdcf49b616fcb72/src/main/scala/ru/org/codingteam/horta/plugins/pet/Pet.scala#L53

**Comment by ForNeVeR** [comment]
It is not him who is responsible.

**Comment by rexim** [comment]
Sure

**Comment by ForNeVeR** [comment]
Are you making fun of me?!

**Comment by rexim** [comment]
Of course not, Mr. von Never!
