### ISSUE TITLE
Pet didn't respond to the first of the two commands given in a rapid succession

### ISSUE THREAD

**Issue by Minoru** [codingteam/horta-hell#324]
[Happened today](http://0xd34df00d.me/logs/chat/codingteam@conference.jabber.ru/2015/07/23.html#05:02:12):

> [05:02:12] \<horta hell> :3 пытается сожрать все, что найдет.
> [05:13:58] \<Minoru> $pet feed
> [05:14:00] \<Minoru> $pet heal
> [05:14:03] \<horta hell> Minoru: :3 будучи в здравом уме и твёрдой памяти отказался от медицинской помощи.
> [05:14:15] \<Minoru> э-э-э, а сообщение о том, что пожрал?
> [05:14:17] \<Minoru> $pet stats
> [05:14:18] \<horta hell> Minoru:
> Кличка: :3
> Здоровье: 28
> Сытость: 98
> Возраст: 6 часов

So judging by the satiation meter, `$pet feed` did work, but where's the message?

(And yes, I do call 2 seconds of pause a "rapid succession". It was 5AM, I was sleepy!)

**Comment by ForNeVeR** [comment]
That is a manifestation of #290.
