### ISSUE TITLE
Improve nickname shortener

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/horta-hell#326]
Horta should have a

> guard against situations when two nicknames are shortened the same way (like, both "m4n71k0r" and "mixer" turn into "m…")?

(extracted from #111)

**Comment by rexim** [comment]
Why do we even need that? To tell apart one shortened person from another? Ok, why do we need to tell the people apart?

**Comment by ForNeVeR** [comment]
We do not want; _they_ want. Consider the following:

    <Hugo> $pet rating
    <horta hell> H...: 1000
                 H...: 1
    <HugeDick> muhaha

**Comment by rexim** [comment]
They can always do `$pet coins` or something.

**Comment by ForNeVeR** [comment]
I think they cannot check other user coins that way. Or they don't need to?

**Comment by rexim** [comment]
I mean, if you are the HugeDick, you can always see you amount of PTCs and guess Hugo's amount just by exclusion.

**Comment by ForNeVeR** [comment]
And what if you're not a HugeDick but just a TinyMixer?

**Comment by rexim** [comment]
Then I will appear as T... which doesn't create any ambiguity.

**Comment by ForNeVeR** [comment]
If you're a TinyMixer then you cannot discover coins of Hugo and HugeDick. But I think that you should have this ability.

**Comment by rexim** [comment]
So, I repeat my question. Why?

**Comment by ForNeVeR** [comment]
Because you see only `H...` and `H...` and cannot distinguish them.

**Comment by rexim** [comment]
You don't understand! My point is we don't need any feature that enables us to distinguish those people. See my comment https://github.com/codingteam/horta-hell/issues/111#issuecomment-124060896

**Comment by ForNeVeR** [comment]
Hm.

**Comment by rexim** [comment]
:D

**Comment by rexim** [comment]
Speaking seriously, I don't mind. :) I think that's a good improvement.

**Comment by ForNeVeR** [comment]
I don't think the proposed situation still creates any problems.
