### ISSUE TITLE
livecoding.tv support

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/horta-hell#343]
We could support livecoding.tv as a chat service.

Maybe some additional tasks should be done first, I'll evaluate them.

**Comment by rexim** [comment]
dkjsddhj

**Comment by hagane** [comment]
that could be... untrivial. the only prior art i found is Cristy94/livecoding-chat-bot and it just piggybacks on a browser.

**Comment by rexim** [comment]
I thought you can connect to livecoding.tv's chat via XMPP https://gist.github.com/zachhanson94/a6ac4508ec025cc27e5c

**Comment by rexim** [comment]
But from the comments we can see that this information is probably outdated. :)

**Comment by rexim** [comment]
Just saw someone using a thirdparty XMPP client to connect to livecoding chat. So it's still possible. Zero effort required for this feature.

**Comment by rexim** [comment]
Well, not completely zero. Maybe we need to register an account for Horta at least. :)

**Comment by rexim** [comment]
![](http://i.imgur.com/6xsEevm.png)

Nothing is required for this feature. Just follow think about Horta as a thirdparty client and follow: http://blog.livecoding.tv/2015/11/21/how-to-chat-onal-xmpp-client/
