### ISSUE TITLE
Loses private messages

### ISSUE THREAD

**Issue by Minoru** [codingteam/horta-hell#361]
[Rexim sent me a couple of messages](http://0xd34df00d.me/logs/chat/codingteam@conference.jabber.ru/2015/12/29.html#23:33:37), but only the second one was delivered [when I entered the room](http://0xd34df00d.me/logs/chat/codingteam@conference.jabber.ru/2015/12/30.html#10:03:26).

It might be due to the fact that I was kicked out of the conference right upon the join, but my client didn't display the first message, so maybe it wasn't even sent?

**Comment by ForNeVeR** [comment]
Well, that's either your server problem with jabber.ru (so it's not a Horta bug) or codingteam.org.ru problem with jabber.ru (yes, it have issues) and, too, not a direct Horta bug. Either way, this problem should be fixed by #290, so I'm closing this.
