### ISSUE TITLE
Twitter integration

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/horta-hell#373]
Horta should be able to relay messages from Twitter. It would be good to automatically send messages from https://twitter.com/tsoding, for example.

**Comment by hagane** [comment]
That would be nice. Actually, I think the data-gathering part of this smorgasborg should be a separate application that will provide a datafeed for the Horta itself. The architecture is getting kinda cluttered as it is, and implementing any other kind of integration (like an RSS feed from https://fornever.me, for example) wil clutter it even more.

**Comment by ForNeVeR** [comment]
I am not _sure_ we want to separate our architecture in such way, but that's one option.

**Comment by hagane** [comment]
[![I'm not entirely sure...](https://img.youtube.com/vi/Tak0BV88h1c/0.jpg)](https://www.youtube.com/watch?v=Tak0BV88h1c)
Same here,.either. Well, I can name some problems that can arise even with constraining the inbuilt integration to twitter only. OTOH we will have to develop a separate service with all the boilerplate -- and from what I reckon, horta deployment is not the simplest thing in the world as it is.

**Comment by ForNeVeR** [comment]
I disagree regarding deployment process currently. It's simple: you just fill a config file (and even the default settings are okay), and that's it. We have a bit complicated production process, but it's not mandatory.

Maybe we could add an option where horta will self-host its messaging service and an another option of dedicated service? Dunno.

**Comment by ForNeVeR** [comment]
@rexim, @Minoru, any suggestions regarding splitting horta into multiple linked projects will be appreciated.

**Comment by hagane** [comment]
Well... first thing is, any service we will want to integrate with will want to either push messages to us by calling an HTTP API or expect us to poll it's own HTTP API. (Twitter offers both, from what I gather)

The problem with the pull model is, we do not have any convenient points for horta to know it needs to query Twitter API for new tweets -- like a website that sends a request to Twitter and integrates it's response into the data it sends to the user. So we'll have to perform semi-continuous polling -- and that can and will clog Akka's internal thread pool. Networking *is* slow.

As for the push model... I do not think integrating even a semi-compliant HTTP server into a chatbot has even a semblance of sanity. Not that I'm implying that we are to do things sane and square, and should not write our own http server, but still... HTTP is one of the things you either do full-time or let someone else do them full-time for you.

**Comment by Minoru** [comment]
I can't claim any knowledge of Horta architecture—I only know things mentioned in "How to write a plugin" guide.

I don't see much sense in splitting things out into services unless they're different enough from the rest of the system. Twitter integration sounds like yet another plugin, not a completely separate service. It seems to me that we can add another plugin trait that, unlike the existing ones, will monitor *external* resource (like Twitter API or RSS feed) and act on data received from there.

I don't know how tightly plugins are coupled with the rest of the system. Can we disable them at build time? I imagine one might want to do so if one doesn't need Twitter or RSS (because these things most certainly will require external dependencies).

**Comment by hagane** [comment]
@Minoru is right. That's exactly how external services should be exposed to plugins. To clarify, I am more concerned about how exactly the data from said services will be gathered.

**Comment by hagane** [comment]
And yes, polling external APIs or receiving requests from external services IS kinda different from the rest of the system.
Wait, that reminds me! There's a codingteam/horta-web project. What's it andivionian status? Is it even alive? Enlighten me, someone =)

**Comment by Minoru** [comment]
Isn't Akka like Erlang? Can't we create a process per external resource (API endpoint, RSS feed etc.) that will sleep most of the time, waking up occasionally to check for updates?

The idea of plugins that query external sources *is* different from the rest of the system which, judging by documented plugin traits, is built around passing MUC-related stanzas to plugins. But I see the addition of new trait as restoring the symmetry and not as breaking the existing system: plugins will be able to both call [external resources] and be called [by Horta's internals].

Now, if a plugin wants to do something really heavyweight, it's only logical to split that stuff into separate service and then write a lightweight plugin to query that service. But reading from Twitter (or RSS) don't fit under "heavyweight tasks" no matter how you squint.

**Comment by hagane** [comment]
In spirit -- yes, Akka is like Erlang. Capabilities differ much though, It's more like Smalltalk on milspec steroids inside. And I'm not saying that the plugins themselves should live outside of a horta instance, only the code that actually gathers data shoud be.

The thing is, web APIs in the wild have a lot of variation to them, so one cannot simply cover them all with one trait -- without it being a wrapper for the actual implementation, like a `JabberProtocol` is effectively a wrapper for the Smack, that handles it's own concurrency and stuff. It is, though, not a plugin (in a horta sense of the term) and is a special case, because XMPP is, currently, the only way for horta to interact with the outside world.

And yes, while fetching some data from a web API is not a terribly "heavy" task, that is, it does not involves any serious number crunching -- yet it does involves a lot of waitng for the server to regurgitate the request and the data to actually pass through the OSI Layers both ways uphill. And 
t͍̜͇̰́ẹ͇̣̝͜r̘͍͈̜͙͓r̬̩i͎̱͙̦̜̲͜b͇̲̭̖̜̘ͅl͎͢e̺͕͖̺̟͇͚ ͉̮̼͉̹̜t͕̪̜̟̬͚h̰i̵̺̝͔ṋ̻̺͘g̢̝͖̹̮̹͔s͍͉͍̼̜ͅ w͎̱̙̖̲ͅį̬̦͙l̙̪̙͓͍͉͟l͝ ̢h͎̗̮a͖̺͍̦̟͉p̰̘͍̱p͈͍̟̭̗̮͇͡e̼̼̘̺͠n͚̣̪̭͘ if you put a thread to sleep in a middle of actor's `receive` N̫͍͕̣̤ͭͣͩ̽̎̽ͅṎ̶́̔̓ͫ ͇ͦ͛̑̅̚P̰̥̮̠ͪL̿̃̂̒̅ͤ͡E̘̹͍͎͎͍̩̽̑̄ͣ͒̌A̧̝ͪ͂S̶̺̲̖̞͉̭̄͂ͧ̎̒Ęͣ̽̽̓͐͂̃ ̼̟̗͋ͨN̼͑̈́͗ͯͯ̏͝O̜͎̰ͩ͐̒̏ͣ̓

So I actually propose to take out the code that actually speaks with APIs outside and present the results to horta as an uniform datafeed, that plugins can consume without actually needing to know how to interact with the original source of this data, or even catching wind of that source queerness, if any.

**Comment by Minoru** [comment]
At this point I'd like to remind everyone that I'm not an active 
contributor and in all probability won't end up implementing any of 
this. So in the spirit of meritocracy, my responses can be safely 
ignored.


@hagane, I understand your concern about encapsulating the queerness of 
APIs. But I don't find your arguments convincing; I suspect I might be 
misunderstanding how Akka works (for now, I just read "Erlang" wherever 
I see "Akka") and how much of a mess Horta is in already.

>The thing is, web APIs in the wild have a lot of variation to them, so 
>one cannot simply cover them all with one trait

Clearly, either you or me misunderstand what is to be abstracted through 
that trait.

I imagined it to have just two methods: `start` and `stop`. `start` 
should accept a callback that plugin can use to send messages to the 
MUC. That's generic enough interface that should fit any message 
producer.

>And yes, while fetching some data from a web API is not a terribly 
>"heavy" task, that is, it does not involves any serious number 
>crunching -- yet it does involves a lot of waitng for the server to 
>regurgitate the request and the data to actually pass through the OSI 
>Layers both ways uphill.

That's the main argument as I see it.

But I don't get why you're even mentioning that. Does Horta use 
cooperative multitasking? Is Horta a single-thread application? Does 
Horta loops over all its plugins, synchronously asking each if it has 
something to send to the MUC? If none of those are the case (which 
I imagine should be true if Akka is *anything* like Erlang), you 
shouldn't worry not only about meager few hundred of milliseconds of 
delay while fetching an RSS feed, but also about things like external 
servers being down: we're in a message-passing land, we'll be notified 
when plugin got all the shit it needs.

>And t͍̜͇̰́ẹ͇̣̝͜r̘͍͈̜͙͓r̬̩i͎̱͙̦̜̲͜b͇̲̭̖̜̘ͅl͎͢e̺͕͖̺̟͇͚ ͉̮̼͉̹̜t͕̪̜̟̬͚h̰i̵̺̝͔ṋ̻̺͘g̢̝͖̹̮̹͔s͍͉͍̼̜ͅ w͎̱̙̖̲ͅį̬̦͙l̙̪̙͓͍͉͟l͝ ̢h͎̗̮a͖̺͍̦̟͉p̰̘͍̱p͈͍̟̭̗̮͇͡e̼̼̘̺͠n͚̣̪̭͘ if you put a thread to sleep in 
>a middle of actor's `receive` N̫͍͕̣̤ͭͣͩ̽̎̽ͅṎ̶́̔̓ͫ ͇ͦ͛̑̅̚P̰̥̮̠ͪL̿̃̂̒̅ͤ͡E̘̹͍͎͎͍̩̽̑̄ͣ͒̌A̧̝ͪ͂S̶̺̲̖̞͉̭̄͂ͧ̎̒Ęͣ̽̽̓͐͂̃ ̼̟̗͋ͨN̼͑̈́͗ͯͯ̏͝O̜͎̰ͩ͐̒̏ͣ̓

That's a technicality, but still: I meant for threads to put 
*themselves* to sleep. They should basically run an infinite loop: fetch 
the data, process it, send messages to MUC (if any), go back to sleep.

>So I actually propose to take out the code that actually speaks with 
>APIs outside and present the results to horta as an uniform datafeed

That can be one step farther: XMPP can be considered as one of "outside 
API", so XMPP stanzas should be put onto that datafeed you mention, too.

That's a joke. This solution seems to be an overkill to me. But then, 
maybe I underestimate how cluttered the system is currently is; maybe it 
is advantageous to split stuff out into separate entities.


Sorry, I've been editing this reply for more than half an hour, now, and 
it's not getting any clearer. Please ask questions if I didn't express 
myself properly, somewhere.

**Comment by Minoru** [comment]
Actually, I don't even know why I started commenting here. I clearly don't know enough about the current architecture to advice you on its evolution, and general hand-waving is not much of a help.

**Comment by ForNeVeR** [comment]
@hagane 

> we'll have to perform semi-continuous polling -- and that can and will clog Akka's internal thread pool. Networking *is* slow.

That's not right in general. Networking *is* slow but networking have nothing to do with thread pool. Good HTTP library should publish its results using some sort of future/promise-style API and use single thread (or _small_ separated pool of threads) together with select/poll/libevent/whatever system-level API.

In all of your messages you seem to continuously express the idea that querying HTTP requires a big amount of _synchronous thread blocking, waiting or sleeping_, and that's simply not right. We may use something like Socko or Akka-HTTP or even just a separated thread pool with blocking and waiting to avoid blocking of Akka internal threads, but I am not sure if that even necessary if we just use standard (or whatever) Future HTTP API. That's not such a big problem.

> There's a codingteam/horta-web project. What's it andivionian status? Is it even alive?

Well, it's technically alive, but currently I'm not deploying it into production due to reason stated in #14: it's extremely slow. We need to fasten it a bit and after that we'll have a solution that can communicate to the rest of horta through database.

Although database-styled IPC is not the best way of doing things, so maybe it'd be a better idea to make something more convenient for IPC-related purposes. Currently horta-web just serves some of the horta data through HTTP and there's no conventional IPC at all.

Regarding overall idea of creating an abstraction layer around all kind of data-sources such as RSS or Twitter or whatever shit else exists - I'm in. I can see architectural pros of this way of thinking. And it would be better to create this abstraction before we start implementing concrete plugins.

But I don't think we need to use a separate process of deployment unit for this purpose. It would be an overkill IMO. We may discuss further.

**Comment by ForNeVeR** [comment]
I think that we got the consensus here. Agreed.

**Comment by hagane** [comment]
I'll get on it then.

**Comment by hagane** [comment]
Found myself in need for some clarification from @ForNeVeR.
I envision twitter integration like this: Horta has an account on Twitter and is following one or more users, like @Tsoding, for example. When one of the following users posts a tweet, said tweet is relayed by Horta to the chatrooms where it is present.
Is this correct or did I misunderstood something?

**Comment by ForNeVeR** [comment]
I wasn't thinking about horta Twitter account at all. If that's the way it works (horta need its personal account) - well, then okay.

I thought we can just poll tweets from some configured users such as @tsoding and that's it. If the way you describe it is the only way - we accept it.

The main problem here is that I'm not aware of Twitter API capabilities and restrictions, and can make some incorrect assumptions based on that.

**Comment by hagane** [comment]
We actually can marry horta to @tsoding, if that's desirable; that will not require any significant changes =) IMO a solution with a separate horta account and following on twitter is more flexible and extendable, so I'll go with it.  We may need to implement some filtering later, so chatrooms won't get firehosed with tweets from everyone and their pet yoghurt colonies though.

**Comment by ForNeVeR** [comment]
I agree.
