### ISSUE TITLE
Endless blood streams

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/horta-hell#375]
Horta does not stop after it enters blood-gore-destroy mode: http://0xd34df00d.me/logs/chat/codingteam@conference.jabber.ru/2016/04/06.html#09:21:45

Need to check logs and the corresponding code.

**Comment by ForNeVeR** [comment]
Well, I was able to reproduce these shits. Here're the quick steps to do that:

1. Enable **permanent** BLOOD GORE DESTROY at [`MarkovPlugin.scala`:97](https://github.com/codingteam/horta-hell/blob/03866ed63a0dbded1733c32b0a11da92228dd29c/src/main/scala/ru/org/codingteam/horta/plugins/markov/MarkovPlugin.scala#L97).
2. Add "random" exception after connecting to room at [`JabberProtocol.scala`:75](https://github.com/codingteam/horta-hell/blob/03866ed63a0dbded1733c32b0a11da92228dd29c/src/main/scala/ru/org/codingteam/horta/protocol/jabber/JabberProtocol.scala#L75). Just

    ```
        if (Math.random() < 0.7) {
          throw new Exception("Restart!")
        }
    ```
3. Disable "deadline sleep" at [`JabberPlugin.scala`:172](https://github.com/codingteam/horta-hell/blob/03866ed63a0dbded1733c32b0a11da92228dd29c/src/main/scala/ru/org/codingteam/horta/protocol/jabber/JabberProtocol.scala#L172).
4. Start Horta, print `$say` into any room _(maybe you'll need to restart it a couple of times to get the "Restart!" message in your logs. The point here is to try to enter the room multiple times in one Horta session)_. And here it comes!

Here's what happening:

1. Horta attaches `MessageAutoRepeater` to the room it enters at [`JabberProtocol.scala`:67-69](https://github.com/codingteam/horta-hell/blob/03866ed63a0dbded1733c32b0a11da92228dd29c/src/main/scala/ru/org/codingteam/horta/protocol/jabber/JabberProtocol.scala#L67-L69).
2. After the repeater has been attached, our test exception fires.  This emulates a network error that can be triggered anywhere inside of `muc.join`, for example.
3. The flow enters the `catch` block and schedules reconnection to this room.
4. Sooner or later, Horta enters the room successfully. Please note that we have **multiple** MessageAutoRepeaters registered at this point for the target room.
5. After any message sent to the server fails due to the server limits, all of our MessageAutoRepeaters tries to send this message again. It's likely that any number of those messages will also exceed server limits, so every MessageAutoRepeater will be triggered again by messages sent by other MessageAutoRepeaters, and so on. Message count raises exponentially, B̤̪̞͚̭̬̭̓ͤ̀l̝̺o̷̼ͨ̂ỏ̬̖̦̘̱̹͍̃ͥ̾̇́̇͞dͮ͆ͬ͟ ͨͭ͗̋̀S̢̺̥̤͉̎ͮṭ̶͚̲̘͓ͭ̿̋ͨ̃R̡̩͎̹ͩͥ͑̍ͅE͌A̜̍́ͥͩ͛M̪̲ͥ̏ͫ̋͠Ṧ̜͌̅̈́ͬ̔ ̜̦̪̗̖̍̽̽̾̏̀s̞̾ͨt͕̽͛ͫ̈́̀a̰̗̭̮̝̤͌ͯr͑͑҉̠̱͕̗̣ͅt̞̟̥͚ͪͩͩ́̽ ̮̮̩̞͑ͤ̿̐̃̚t̡̩̰̗̦̰̭̝͑͊̚o̝̲͇͇̯͓ͅ ͈̝͉ͅF̥̣͎͚̉ͩ̈͊ͮ̚̚͝L̳̰̩̥͎̇̏ͬͯ͛ò̙̺̳̦̜͙̟W̲͚͕ͪ.

The changes to `MarkovPlugin` and `JabberProtocol.sendMessage` are here to enter the error state more reliable. It's totally possible to get the error in unmodified Horta. Main reason here is the problem triggered while joining the room.

I think we should just extract the `MessageAutoRepeater` connection from the `try`/`catch` block, and attach that only if the joining was successful.

**Comment by Minoru** [comment]
> attach that only if the joining was successful

But that's exactly what we have now, isn't it? The problem is that we don't remove the handler when exception fires.

**Comment by ForNeVeR** [comment]
No, currently we're attaching the repeater _first_, and trying join the room afterwards.

I'll extract the repeater from the try-catch block, so we'll have only two valid states: either the room has been entered and the repeater has been attached, or neither of them succeed.

**Comment by Minoru** [comment]
Ah, my bad. You're right.

But I don't see any code removing the handler. What happens if Horta is kicked out of the room? What if it loses connection to the server? Are all these situations accounted for?

**Comment by ForNeVeR** [comment]
If Horta is kicked from the room, then currently nothing happens. There's an another task for that: #352.

In case of a general network errors anywhere except this damned `try` block, the whole `JabberProtocol` will be killed, recreating the XMPP connection in process. We have this case covered I'd say.
