### ISSUE TITLE
s/{from}/{to}/ does not check presense of {from} in the message

### ISSUE THREAD

**Issue by ChALkeR** [codingteam/horta-hell#378]
It should probably ignore the replacement if nothing was actually changed in the message. A better option: it could search several messages back to find the first matched one.

Current situation:
```
User: foo
User: bar
User: s/foo/baz/
horta hell: User: bar
```

**Comment by Minoru** [comment]
@ForNeVeR, are you still on this? It looks to me like this can be fixed with just a couple lines of code. Should I submit a PR? Am I missing some hidden problems?

**Comment by ForNeVeR** [comment]
Don't think so. You're free to implement this.
