### ISSUE TITLE
Tweets are shown everywhere instead of only target room

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/horta-hell#393]
Consider this configuration:

```
rooms=codingteam,javascript
codingteam.room=codingteam@conference.jabber.ru
codingteam.locale=ru
codingteam.events=twitter
javascript.room=javascript@conference.jabber.ru
javascript.locale=ru
```

Whenever Horta see any Tweet, he posts it to **both** codingteam and javascript rooms. I thought that it should send the tweets only to rooms marked by `events=twitter`.

**Comment by hagane** [comment]
It should indeed behave like this. I'll look into in straight away.
