### ISSUE TITLE
Disable pet per chat

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/horta-hell#400]
Not everyone wants a pet plugin to be active in their MUC. We should add a configuraion option to disable pet (or to enable it) in the selected chats.

**Comment by ttldtor** [comment]
Maybe we should make all plugins desableable?

**Comment by rexim** [comment]
@ttldtor @ForNeVeR #170

**Comment by ForNeVeR** [comment]
Yes that's an ongoing idea, see #170. But disabling the pet plugin is somewhat more urgent than a more general mechanism.

**Comment by rexim** [comment]
AHAHAHAHA
